### ISSUE TITLE
PlaySound error in 7.3

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/Broker_Equipment#15]
This is throwing an error since 7.3 went live.
I looked the error up and found this thread:
https://us.battle.net/forums/en/wow/topic/20758856637
Another search found me this thread which shows which number to use:
http://www.wowinterface.com/forums/showpost.php?p=324045&postcount=7

So I've changed line 73 to:
`		PlaySound(856)
`
It works like it used to then.

**Comment by p3lim** [comment]
https://www.townlong-yak.com/framexml/live/SoundKitConstants.lua
^ List of them all if you're interested.

**Comment by Cluuey** [comment]
Cheers, that is interesting although I don't know enough to use it.
"Just enough to be dangerous, not enough to be really helpful." ;-)
